export const RoleType = {
  STANDARD: "STANDARD",
  SUPER: "SUPER",
  READONLY: "READONLY",
  DENYING: "DENYING",
  STRICTLY_DENYING: "STRICTLY_DENYING",
};

export const PermissionType = {
  SCREEN: "SCREEN",
  ENTITY_OP: "ENTITY_OP",
  ENTITY_ATTR: "ENTITY_ATTR",
  SPECIFIC: "SPECIFIC",
  U: "UI",
};
